config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/participant.rb
class Participant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>

</head>

<h1>Test Page</h1>

<p id="link1"><%= link_to 'Admin site', new_admin_user_session_path%></p>

<p class="invisible"></p><%participant=Participant.find_by(id:'1');%></p>

<div><p class="title">Participant #1</p>
<p class="bold">First Name:</p><p class="content"><%=participant.first_name%></p>
<p></p><p class="bold">Last Name: </p><p class="content"><%=participant.last_name%></p>
<p></p><p class="bold">Mobile Phone: </p><p class="content"><%=participant.mobile_phone%></p>
<p></p><p class="bold">Home Phone: </p><p class="content"><%=participant.home_phone%></p>
<p></p><p class="bold">Email: </p><p class="content"><%=participant.e_mail%></p>
<p></p><p class="bold">Age: </p><p class="content"><%=participant.age%></p>
<p></p><p class="bold">About: </p><p class="content"><%=participant.about%></p>
<p></p>
 
 
</div>
	
</html>1